---
- name: configure hostname
  hostname: name="{{ inventory_hostname }}" 
  become: true

- name: add hostname to /etc/hostname
  lineinfile:
    dest: /etc/hostname
    regexp: '.*'
    line: '{{ ansible_hostname }}'
    state: present
  become: true

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ ansible_hostname }}'
    state: present
  become: true

- name: include vars
  include_vars:
    file: roles/postgresql/vars/main.yml
  become: true